In [3]:
import numpy
numpy.__version__

'1.26.4'

In [5]:
import numpy as np

In [7]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\nikhi\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\nikhi\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [11]:
# data types in python are dynamically inferred
result = 0
for i in range(100):
    result += i

In [13]:
# this would cause an error in c
x = 4
x = "four"

In [19]:
# a single int in python contains 4 pieces

SyntaxError: invalid syntax (1110603167.py, line 2)

In [21]:
# python int is a pointer to a position in memory containing all the 
# python object information including bytes that contain the int value


In [23]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [25]:
type(L[0])

int

In [29]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [31]:
type(L2[0])

str

In [33]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [37]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [43]:
# numpy arrays need to contain same type
# if no match it'll upcast
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [45]:
# explicitly set the data type of resulting array
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [47]:
# numpy can be explicitly multidimensional
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])
# inner lists are treated as rows

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [49]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
# create a 3x5 floating point array filled with 1s
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
# create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [59]:
# create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
# create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [63]:
# create a 3x3 array uniformly distributed 
# random values between 0 and 1
np.random.random((3, 3))


array([[0.00775294, 0.8956408 , 0.63307686],
       [0.55404608, 0.12062438, 0.8426691 ],
       [0.6093552 , 0.55106546, 0.64676438]])

In [65]:
# create a 3x3 array of normally distributed random values 
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.86317946, -0.5519944 , -0.11293265],
       [ 1.24457396, -1.08151878,  1.2411227 ],
       [ 1.15600091,  1.05295173, -1.46388987]])

In [67]:
# create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[2, 6, 6],
       [7, 3, 6],
       [4, 3, 0]])

In [69]:
# create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
# create an uninitialized array of three integers
# the values will be whatever happens to already exist at that memory location
np.empty(3)


array([1., 1., 1.])

In [75]:
# when constructing an array you can specify them using a string
np.zeros(10, dtype = 'int16')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)