In [3]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [5]:
print("x3 ndim: ", x3.ndim)

x3 ndim:  3


In [11]:
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 shape:  (3, 4, 5)
x3 size:  60


In [13]:
print("dtype: ", x3.dtype)

dtype:  int32


In [17]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize:  4 bytes
nbytes: 240 bytes


In [19]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [21]:
x1

array([5, 0, 3, 3, 7, 9])

In [27]:
x1[0]
x1[4]

7

In [29]:
x1[-1]

9

In [31]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [33]:
x2[0, 0]

3

In [35]:
x2[2, -1]

7

In [39]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [43]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

In [45]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
# prints first 5 elements
x[:5]

array([0, 1, 2, 3, 4])

In [53]:
# elements after index 5
x[5:]

array([5, 6, 7, 8, 9])

In [55]:
x[4:7]

array([4, 5, 6])

In [57]:
x[::2]

array([0, 2, 4, 6, 8])

In [59]:
x[1::2]

array([1, 3, 5, 7, 9])

In [61]:
# all elements reversed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [63]:
x[5::-2]

array([5, 3, 1])

##### Multidimensional subarrays

In [66]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [68]:
# prints 2 rows three columns
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [72]:
# all rows every other column
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [74]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [76]:
# first column of x2
print(x2[:,0])

[12  7  1]


In [78]:
# equivalent to x2[0, :]
print(x2[0])

[12  5  2  4]


In [82]:
# no copy views
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [84]:
# extracting 2x2 subarray from above array
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [86]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [88]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [90]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])


array([1, 2, 3, 3, 2, 1])

In [92]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [94]:
grid = np.array([[1, 2, 3],
[4, 5, 6]])

In [96]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [98]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [100]:

x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])

In [104]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [106]:
 # horizontally stack the arrays
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])